### ISSUE TITLE
Feature Request - Set all vertical metrics directly

### ISSUE THREAD

**Issue by kenmcd** [ftCLI/FoundryTools-CLI#164]
I would like to be able to set these directly:
OS/2 `sTypoAscender`, `sTypoDescender`, `sTypoLineGap`
and `usWinAscent`, `usWinDescent`
Like it is possible now in `ftcli hhea` to set `ascent`, `descent`, `linegap` directly to exact specified settings.

So one would be able to "fix" all the vertical metrics to exactly the desired settings.

Thanks!  Love this tool.

**Comment by ftCLI** [comment]
Thanks!

I have already introduced a `set-attrs` command in [ftCLI 2](https://github.com/ftCLI/FoundryTools-CLI-2) (still work in progress), that allows to set those attributes.

`ft-cli os2 set-attrs --typo-ascender 750 --typo-descender -250 --typo-line-gap 200 --win-ascent 900 --win-descent 300`

(I temporary use `ft-cli` instead of `ftcli` to install them side by side).

I'm going to add them also to v1 and will release later

**Comment by ftCLI** [comment]
Done: https://github.com/ftCLI/FoundryTools-CLI/releases/tag/v1.1.12

You can find everything under the `ftcli os2 set-attrs` subcommand

**Comment by kenmcd** [comment]
Fan-freakin-tastic.
Thank you!
