### ISSUE TITLE
No way to clear fsSelection bit 6 

### ISSUE THREAD

**Issue by ddaanniiieeelll** [ftCLI/FoundryTools-CLI#182]
Hello :)

I realised that there is no `--no-regular` or `-n-rg` option to clear bit 6 in the fsSelection in the OS/2 table.

While this is not flagged as an error in the tools I know, the spec still states that it shouldn’t be set except it is the Regular weight of the family.

https://learn.microsoft.com/en-us/typography/opentype/spec/os2#fsselection

**Comment by ftCLI** [comment]
There’s no such option because the regular bit is cleared when the bold or italic flags are set, and it’s set when both bold and italic bits are cleared. So, setting as non-regular a font that is not italic neither bold would produce an invalid result. I avoided to add a `—no-regular` option to prevent users from doing a wrong thing.

**Comment by ddaanniiieeelll** [comment]
Interesting, could you provide sources where this would produce an invalid result (or font for that matter)?
I read the OTspec in the way that it would be alright to have all bits cleared in fonts that are neither Bold, Italic, Bold Italic or the fonts "Regular" weight.

The functionality of it being cleared when setting Bold or Italic bits works very well (I post processed >1000 fonts this week with your tool).

BTW your tool was a life saver this week for me, outstanding work :)

**Comment by ftCLI** [comment]
I intend the spec this way: bit 6 must be set to 1 if nameID 2 is “Regular”, 0 otherwise. But I’ll review this next week and I’m open to add a `—no-regular/-no-rg` option in case. Anyway, I think that fontbakery returns an error if nameID 2 is Regular and bit 6 is 0.

Thanks indeed for the endorsement, I think ftCLI is a good idea with an ugly realisation. I’m working on version 2 (https://github.com/ftCLI/FoundryTools-CLI-2) where writing snippets and running them with a Runner class eases the pain and reduces duplication by a lot.

**Comment by ddaanniiieeelll** [comment]
I’ll check again with fontbakery, but in my tests so far they didn’t raise this as an error.
Anyways, I can’t look at fonts anymore for today.
Will get back if I have more information on this.

**Comment by ftCLI** [comment]
IBM Plex Sans has the fsSelection bit 6 set only in the Regular style.

Running `fontbakery check-universal` on IBMPlexSans-Semibold.ttf returns the following error:

```
 >> com.google.fonts/check/fsselection
    Checking OS/2 fsSelection value.
    with IBMPlexSans-SemiBold.ttf

    Rationale:

    The OS/2.fsSelection field is a bit field used to specify the stylistic qualities of the font - in particular, it specifies to some operating systems whether the font is italic (bit
    0), bold (bit 5) or regular (bit 6).

    This check verifies that the fsSelection field is set correctly for the font style. For a family of static fonts created in GlyphsApp, this is set by using the style linking
    checkboxes in the exports settings.

    FAIL OS/2 fsSelection REGULAR bit should be set. [code: bad-REGULAR]

    Result: FAIL
```

The code of the fontbakery check is here: https://github.com/fonttools/fontbakery/blob/2bb3b91191cc9f71799e20e73b6d82c9a14966ba/Lib/fontbakery/checks/opentype/os2.py#L354

**Comment by ddaanniiieeelll** [comment]
The more I think about it the more your argument makes sense to me.
I also talked to people on my team and apparently this is no problem for us and also I was more or less the only one worrying about this.

**Comment by ftCLI** [comment]
If it’s ok I close this issue.

Thanks indeed for using ftCLI and reporting issues!
